with open('src/views/home.vue', 'r', encoding='utf-8') as f:
    content = f.read()

# 修改funnel配置中的legend位置
# 将bottom:"auto"改为bottom:8，将left:"left"改为left:"center"
content = content.replace(
    'funnel: {"tooltip":{"backgroundColor":"rgba(255,255,255,.97)","textStyle":{"color":"#334155"},"extraCssText":"box-shadow: 0 8px 24px rgba(0,0,0,.12); border-radius: 10px; border: 1px solid #f1f5f9; padding: 10px 16px;"},"backgroundColor":"transparent","color":["#4facfe","#a18cd1","#43e97b","#fa709a","#38f9d7","#fbc2eb","#667eea","#fee140","#f093fb","#30d4c8"],"title":{"borderType":"solid","padding":2,"shadowOffsetX":0,"backgroundColor":"transparent","borderColor":"#ccc","shadowOffsetY":0,"shadowBlur":0,"bottom":"auto","show":true,"right":"auto","top":8,"borderRadius":0,"left":"center","borderWidth":0,"textStyle":{"textBorderWidth":0,"color":"#1e293b","textShadowColor":"transparent","fontSize":15,"lineHeight":22,"textShadowOffsetX":0,"textShadowOffsetY":0,"textBorderType":"solid","fontWeight":"700","textBorderColor":"#ccc","textShadowBlur":0},"shadowColor":"transparent"},"legend":{"padding":5,"itemGap":14,"shadowOffsetX":0,"backgroundColor":"transparent","borderColor":"#ccc","shadowOffsetY":0,"orient":"horizontal","shadowBlur":0,"bottom":"auto","itemHeight":10,"show":true,"icon":"roundRect","itemStyle":{"borderType":"solid","shadowOffsetX":0,"borderColor":"inherit","shadowOffsetY":0,"color":"inherit","shadowBlur":0,"borderWidth":0,"opacity":1,"shadowColor":"transparent"},"top":"auto","borderRadius":0,"lineStyle":{"shadowOffsetX":0,"shadowOffsetY":0,"color":"inherit","shadowBlur":0,"width":"auto","type":"inherit","opacity":1,"shadowColor":"transparent"},"left":"left","borderWidth":0,"width":"auto","itemWidth":10,"textStyle":{"textBorderWidth":0,"color":"#64748b","textShadowColor":"transparent","ellipsis":"...","overflow":"none","fontSize":12,"lineHeight":16,"textShadowOffsetX":0,"textShadowOffsetY":0,"textBorderType":"solid","fontWeight":"500","textBorderColor":"transparent","textShadowBlur":0},"shadowColor":"rgba(0,0,0,.3)","height":"auto"},"series":{"itemStyle":{"borderType":"solid","shadowOffsetX":0,"borderColor":"#000","shadowOffsetY":0,"color":"","shadowBlur":0,"borderWidth":0,"opacity":1,"shadowColor":"#000"},"label":{"borderType":"solid","rotate":0,"padding":8,"textBorderWidth":0,"backgroundColor":"transparent","borderColor":"#fff","color":"#fff","show":true,"textShadowColor":"transparent","distanceToLabelLine":5,"ellipsis":"...","overflow":"none","borderRadius":4,"borderWidth":0,"fontSize":12,"lineHeight":18,"textShadowOffsetX":0,"position":"inside","textShadowOffsetY":0,"textBorderType":"solid","textBorderColor":"#fff","textShadowBlur":0},"labelLine":{"show":true,"length":14,"lineStyle":{"shadowOffsetX":0,"shadowOffsetY":0,"shadowBlur":0,"width":1.5,"type":"solid","opacity":0.8,"shadowColor":"rgba(0,0,0,.1)"},"length2":18,"smooth":0.3}}}
    ,
    'funnel: {"tooltip":{"backgroundColor":"rgba(255,255,255,.97)","textStyle":{"color":"#334155"},"extraCssText":"box-shadow: 0 8px 24px rgba(0,0,0,.12); border-radius: 10px; border: 1px solid #f1f5f9; padding: 10px 16px;"},"backgroundColor":"transparent","color":["#4facfe","#a18cd1","#43e97b","#fa709a","#38f9d7","#fbc2eb","#667eea","#fee140","#f093fb","#30d4c8"],"title":{"borderType":"solid","padding":2,"shadowOffsetX":0,"backgroundColor":"transparent","borderColor":"#ccc","shadowOffsetY":0,"shadowBlur":0,"bottom":"auto","show":true,"right":"auto","top":8,"borderRadius":0,"left":"center","borderWidth":0,"textStyle":{"textBorderWidth":0,"color":"#1e293b","textShadowColor":"transparent","fontSize":15,"lineHeight":22,"textShadowOffsetX":0,"textShadowOffsetY":0,"textBorderType":"solid","fontWeight":"700","textBorderColor":"#ccc","textShadowBlur":0},"shadowColor":"transparent"},"legend":{"padding":5,"itemGap":14,"shadowOffsetX":0,"backgroundColor":"transparent","borderColor":"#ccc","shadowOffsetY":0,"orient":"horizontal","shadowBlur":0,"bottom":8,"itemHeight":10,"show":true,"icon":"roundRect","itemStyle":{"borderType":"solid","shadowOffsetX":0,"borderColor":"inherit","shadowOffsetY":0,"color":"inherit","shadowBlur":0,"borderWidth":0,"opacity":1,"shadowColor":"transparent"},"top":"auto","borderRadius":0,"lineStyle":{"shadowOffsetX":0,"shadowOffsetY":0,"color":"inherit","shadowBlur":0,"width":"auto","type":"inherit","opacity":1,"shadowColor":"transparent"},"left":"center","borderWidth":0,"width":"auto","itemWidth":10,"textStyle":{"textBorderWidth":0,"color":"#64748b","textShadowColor":"transparent","ellipsis":"...","overflow":"none","fontSize":12,"lineHeight":16,"textShadowOffsetX":0,"textShadowOffsetY":0,"textBorderType":"solid","fontWeight":"500","textBorderColor":"transparent","textShadowBlur":0},"shadowColor":"rgba(0,0,0,.3)","height":"auto"},"series":{"itemStyle":{"borderType":"solid","shadowOffsetX":0,"borderColor":"#000","shadowOffsetY":0,"color":"","shadowBlur":0,"borderWidth":0,"opacity":1,"shadowColor":"#000"},"label":{"borderType":"solid","rotate":0,"padding":8,"textBorderWidth":0,"backgroundColor":"transparent","borderColor":"#fff","color":"#fff","show":true,"textShadowColor":"transparent","distanceToLabelLine":5,"ellipsis":"...","overflow":"none","borderRadius":4,"borderWidth":0,"fontSize":12,"lineHeight":18,"textShadowOffsetX":0,"position":"inside","textShadowOffsetY":0,"textBorderType":"solid","textBorderColor":"#fff","textShadowBlur":0},"labelLine":{"show":true,"length":14,"lineStyle":{"shadowOffsetX":0,"shadowOffsetY":0,"shadowBlur":0,"width":1.5,"type":"solid","opacity":0.8,"shadowColor":"rgba(0,0,0,.1)"},"length2":18,"smooth":0.3}}}
)

with open('src/views/home.vue', 'w', encoding='utf-8') as f:
    f.write(content)

print("修改完成！")
